### ISSUE TITLE
Launcher Support

### ISSUE THREAD

**Issue by PXshadow** [MilkweedOHOL/OneLifeClient#1]
Hello Milkweed the current launcher looks in release for the client binary by finding the substring "_v" would it be possible for you to change your naming convention slightly to have that in your naming convention like hetuw and awbz. 

also I have given you write access to change any of the data for your client. https://github.com/PXshadow/OpenLifeLauncherAssets/blob/master/clients/milkweed.json

Thanks so much.

**Comment by MilkweedOHOL** [comment]
I changed it. Can your launcher detect?

**Comment by PXshadow** [comment]
Hey Milkweed, 
For some reason the meta data is still different I'm not sure why. 

Here is hetuw:
`<a href="/hetuw/OneLife/tree/OneLife_v260" class="muted-link css-truncate" title="OneLife_v260">`
Milkweed:
`<a href="/MilkweedOHOL/OneLifeClient/tree/v265" class="muted-link css-truncate" title="v265">`

It grabs from the title not the href.

**Comment by MilkweedOHOL** [comment]
<img width="974" alt="スクリーンショット 2019-09-26 17 27 08" src="https://user-images.githubusercontent.com/45931448/65676065-34f39c80-e08a-11e9-9010-673bd5172124.png">
<img width="974" alt="スクリーンショット 2019-09-26 17 27 58" src="https://user-images.githubusercontent.com/45931448/65676073-37ee8d00-e08a-11e9-9485-e4d49b5a5c4e.png">
Do Release name and Tag name have to be same?

**Comment by PXshadow** [comment]
It works now thank you so much! I look forward to using and supporting your mod from here on out with the launcher👍

**Comment by PXshadow** [comment]
Sorry to quick to close, on mac the zipped content needs to be directly in the zip without a folder. otherwise it extracts the folder into the server place but cannot locate the application.

**Comment by PXshadow** [comment]
windows works right now though!

**Comment by MilkweedOHOL** [comment]
<img width="453" alt="スクリーンショット 2019-09-28 21 50 41" src="https://user-images.githubusercontent.com/45931448/65816720-4380b600-e23a-11e9-8822-e48f0a46c4d8.png">
<img width="453" alt="スクリーンショット 2019-09-28 21 51 04" src="https://user-images.githubusercontent.com/45931448/65816722-45e31000-e23a-11e9-9eff-2c9f12a63eed.png">
I extracted Awbz's mod and mine, both of them looks to have the same format.
But if I extract zip files in "clients/awbz/" and "clients/milkweed", they make difference.
<img width="362" alt="スクリーンショット 2019-09-28 22 11 12" src="https://user-images.githubusercontent.com/45931448/65817008-47fa9e00-e23d-11e9-9f26-b64cf7f18359.png">
<img width="362" alt="スクリーンショット 2019-09-28 22 11 07" src="https://user-images.githubusercontent.com/45931448/65817010-4af58e80-e23d-11e9-895b-9afbf0d4848d.png">
why?

**Comment by PXshadow** [comment]
I'm not sure, I can just look for an initial folder on my end and ignore it. I'll shoot for that in the next release of the launcher. Thanks for trying to look into it, not that big of a deal.
