### ISSUE TITLE
OneLife++ v270 Client Does Not Launch

### ISSUE THREAD

**Issue by SalvatoryMalamar** [MilkweedOHOL/OneLifeClient#3]
Hello. I'm running OneLife++ v270 pre-compiled binary on macOS Sierra v10.12.6. The OneLife++ client does not open when launched. No OneLife++ process appears in the activity monitor after trying to launch. There is no error message either. 

The OneLife++ app is in the OHOL game folder. I have done a complete OHOL and OL++ re-install and the issue persists. I also have OneLife+ installed in the same folder.

Macbook Pro Retina, Mid 2012
2.3 GHZ Intel Core i7
8GB Ram
NVIDIA GeForce GT 650M 1024MB

**Comment by MilkweedOHOL** [comment]
I uploaded a  fixed client.
Please download it and try launching.
